#!/bin/bash
# Office-31
python3 train_capan.py --gpu_id 0  --arch resnet50 --seed 0 --dset office --output_dir log/capan/Office31 --s_dset_path /datasets/Office31/amazon.txt --t_dset_path /datasets/Office31/webcam.txt --t_test_path /datasets/Office31/webcam.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01 --batch-size 32  --entropy_tradeoff 0.2 --bottleneck-dim 256 --loss_type 5 --feature_temp 0.05   --feature_norm True 
python3 train_capan.py --gpu_id 0  --arch resnet50 --seed 0 --dset office --output_dir log/capan/Office31 --s_dset_path /datasets/Office31/amazon.txt --t_dset_path /datasets/Office31/dslr.txt --t_test_path /datasets/Office31/dlsr.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.003 --batch-size 32 --entropy_tradeoff 0.2 --bottleneck-dim 256 --loss_type 5 --feature_temp 0.05   --feature_norm True 
python3 train_capan.py --gpu_id 0  --arch resnet50 --seed 0 --dset office --output_dir log/capan/Office31 --s_dset_path /datasets/Office31/webcam.txt --t_dset_path /datasets/Office31/amazon.txt --t_test_path /datasets/Office31/amazon.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0  --threshold 0.8 --lr 0.01 --batch-size 32  --entropy_tradeoff 0.2 --bottleneck-dim 256 --loss_type 5 --feature_temp 0.05   --feature_norm True 
python3 train_capan.py --gpu_id 0  --arch resnet50 --seed 0 --dset office --output_dir log/capan/Office31 --s_dset_path /datasets/Office31/dslr.txt --t_dset_path /datasets/Office31/amazon.txt --t_test_path /datasets/Office31/amazon.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01 --batch-size 32  --entropy_tradeoff 0.2 --bottleneck-dim 256 --loss_type 5 --feature_temp 0.05   --feature_norm True 
# python3 train_capan.py --gpu_id 0  --arch resnet50 --seed 0 --dset office --output_dir log/capan/Office31 --s_dset_path /datasets/Office31/dslr.txt --t_dset_path /datasets/Office31/webcam.txt --t_test_path /datasets/Office31/webcam.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01 --batch-size 32  --entropy_tradeoff 0.2 --bottleneck-dim 256 --loss_type 5 --feature_temp 0.05   --feature_norm True 
# python3 train_capan.py --gpu_id 0  --arch resnet50 --seed 0 --dset office --output_dir log/capan/Office31 --s_dset_path /datasets/Office31/webcam.txt --t_dset_path /datasets/Office31/dslr.txt --t_test_path /datasets/Office31/dslr.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01 --batch-size 32  --entropy_tradeoff 0.2 --bottleneck-dim 256 --loss_type 5 --feature_temp 0.05   --feature_norm True 

# python3 train_capan.py --gpu_id 0 --arch resnet101 --seed 0 --dset visda2017 --output_dir log/capan/visda2017 --s_dset_path /datasets/VisDA2017/train.txt --t_dset_path /datasets/VisDA2017/validation.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 0.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --batch-size 32 --lr 0.001 --feature_temp 1.0 --entropy_tradeoff 0.05 --center_crop



